# Generated by Django 4.2.6 on 2023-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_something_wrong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='json_field',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
