# Generated by Django 4.2.6 on 2023-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_something_wrong',
        ),
        migrations.RemoveField(
            model_name='question',
            name='json_field',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='질문'),
        ),
    ]
